import { Flex } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Sidebar from '../components/Sidebar'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Chat-App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Flex h={'100vh'}>
				<Sidebar />
			</Flex>
		</div>
	)
}

export default Home
